# Lab 1 - Introduction to Python for Machine Learning
Umair Hafeez
CMS ID: 023-24-0473

### Task 1 - Installing Python & Setting Up Environment

In [1]:
import sys
print(sys.version)

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]


### Task 2 - Installing & Importing Libraries

In [3]:
# pip install numpy pandas matplotlib scikit-learn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

print('numpy:', np.__version__)
print('pandas:', pd.__version__)
print('scikit-learn:', sklearn.__version__)

numpy: 2.3.5
pandas: 2.3.3
scikit-learn: 1.7.2


### Task 3 - Data Types

In [4]:
age = 21
gpa = 3.75
name = 'Ayesha'
is_enrolled = True
advisor = None

print(type(age), type(gpa), type(name), type(is_enrolled), type(advisor))

age_str = str(age)
gpa_int = int(gpa)
print(age_str, type(age_str))
print(gpa_int, type(gpa_int))

<class 'int'> <class 'float'> <class 'str'> <class 'bool'> <class 'NoneType'>
21 <class 'str'>
3 <class 'int'>


### Task 4 - Operators

In [5]:
length, width = 12, 5
area = length * width
perimeter = 2 * (length + width)
print('Area:', area, '| Perimeter:', perimeter)

marks = 78
passed = marks >= 50
honors = marks >= 85 and marks <= 100
print('Passed:', passed, '| Honors:', honors)

fruits = ['apple', 'banana', 'mango']
print('banana' in fruits)

Area: 60 | Perimeter: 34
Passed: True | Honors: False
True


Try It - check if marks qualify for Distinction (>=90) or Pass (50-89)

In [6]:
student_marks = 92

is_distinction = student_marks >= 90
is_pass = student_marks >= 50 and student_marks < 90

if is_distinction:
    result = 'Distinction'
elif is_pass:
    result = 'Pass'
else:
    result = 'Fail'

print(student_marks, '->', result)

92 -> Distinction


### Task 5 - Control Structures

In [7]:
score = 82
if score >= 90:
    grade = 'A'
elif score >= 80:
    grade = 'B'
elif score >= 70:
    grade = 'C'
else:
    grade = 'F'
print('Grade:', grade)

total = 0
for n in range(1, 11):
    total += n
print('Sum 1-10:', total)

countdown = 5
while countdown > 0:
    print(countdown)
    countdown -= 1
print('Liftoff!')

Grade: B
Sum 1-10: 55
5
4
3
2
1
Liftoff!


Try It - FizzBuzz 1 to 30

In [8]:
for i in range(1, 31):
    if i % 3 == 0 and i % 5 == 0:
        print('FizzBuzz')
    elif i % 3 == 0:
        print('Fizz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz


### Task 6 - Arrays

In [9]:
from array import array

scores = array('i', [67, 72, 89, 91, 55])
print(scores)
print('Length:', len(scores))
print('Max score:', max(scores))

array('i', [67, 72, 89, 91, 55])
Length: 5
Max score: 91


Try It - array of even numbers 2 to 20

In [9]:
even_numbers = array('i', range(2, 21, 2))
print(even_numbers)

array('i', [2, 4, 6, 8, 10, 12, 14, 16, 18, 20])


### Task 7 - Multi-Dimensional Arrays with NumPy

In [10]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print('Shape:', matrix.shape)
print('Row 0:', matrix[0])
print('Column 1:', matrix[:, 1])
print('Transpose:\n', matrix.T)
print('Row sums:', matrix.sum(axis=1))
print('Column sums:', matrix.sum(axis=0))

zeros = np.zeros((2, 4))
ones = np.ones((2, 4))
seq = np.arange(0, 10, 2)
print(zeros, ones, seq, sep='\n')

Shape: (3, 3)
Row 0: [1 2 3]
Column 1: [2 5 8]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Row sums: [ 6 15 24]
Column sums: [12 15 18]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]


Try It - 4x4 matrix, transpose, row/column sums

In [11]:
my_matrix = np.array([[4, 8, 15, 16],
                       [23, 42, 1, 7],
                       [9, 11, 13, 5],
                       [2, 6, 10, 14]])

print(my_matrix)
print('Shape:', my_matrix.shape)
print('Transpose:\n', my_matrix.T)
print('Row sums:', my_matrix.sum(axis=1))
print('Column sums:', my_matrix.sum(axis=0))

[[ 4  8 15 16]
 [23 42  1  7]
 [ 9 11 13  5]
 [ 2  6 10 14]]
Shape: (4, 4)
Transpose:
 [[ 4 23  9  2]
 [ 8 42 11  6]
 [15  1 13 10]
 [16  7  5 14]]
Row sums: [43 73 38 32]
Column sums: [38 67 39 42]


### Task 8 - Lists, Tuples and Sets

In [12]:
grades = ['B', 'A', 'C']
grades.append('A')
grades.sort()
print('List:', grades)

student = ('Ali', 21, 'Computer Science')
print('Tuple:', student)

course_a = {'Ali', 'Sara', 'Bilal', 'Sara'}
course_b = {'Sara', 'Zain', 'Ali'}
print('Union:', course_a | course_b)
print('Intersection:', course_a & course_b)
print('Only in A:', course_a - course_b)

List: ['A', 'A', 'B', 'C']
Tuple: ('Ali', 21, 'Computer Science')
Union: {'Zain', 'Ali', 'Sara', 'Bilal'}
Intersection: {'Ali', 'Sara'}
Only in A: {'Bilal'}


Try It - two recipes as sets, find common/unique ingredients and combined list

In [13]:
recipe1 = ['flour', 'sugar', 'eggs', 'butter', 'milk', 'vanilla']
recipe2 = ['flour', 'eggs', 'cocoa powder', 'baking soda', 'butter', 'salt']

set1 = set(recipe1)
set2 = set(recipe2)

print('Common:', set1 & set2)
print('Unique to recipe1:', set1 - set2)
print('Unique to recipe2:', set2 - set1)
print('Shopping list:', set1 | set2)

Common: {'butter', 'eggs', 'flour'}
Unique to recipe1: {'sugar', 'vanilla', 'milk'}
Unique to recipe2: {'salt', 'cocoa powder', 'baking soda'}
Shopping list: {'sugar', 'salt', 'milk', 'eggs', 'cocoa powder', 'vanilla', 'butter', 'flour', 'baking soda'}


### Task 9 - Pandas Read/Write Files

In [14]:
data = {
    'Name': ['Ali', 'Sara', 'Bilal', 'Zain', 'Hina'],
    'Quiz1': [8, 9, 6, 7, 10],
    'Quiz2': [7, 10, 8, 6, 9],
}
df = pd.DataFrame(data)
df.to_csv('student_scores.csv', index=False)

df2 = pd.read_csv('student_scores.csv')
print(df2.head())
print(df2.describe())
print('Average Quiz1:', df2['Quiz1'].mean())

    Name  Quiz1  Quiz2
0    Ali      8      7
1   Sara      9     10
2  Bilal      6      8
3   Zain      7      6
4   Hina     10      9
           Quiz1      Quiz2
count   5.000000   5.000000
mean    8.000000   8.000000
std     1.581139   1.581139
min     6.000000   6.000000
25%     7.000000   7.000000
50%     8.000000   8.000000
75%     9.000000   9.000000
max    10.000000  10.000000
Average Quiz1: 8.0


In [15]:
df2['Grade'] = df2['Quiz1'].apply(lambda x: 'A' if x >= 8 else 'B')
df2.to_csv('student_scores_graded.csv', index=False)
print(df2)

    Name  Quiz1  Quiz2 Grade
0    Ali      8      7     A
1   Sara      9     10     A
2  Bilal      6      8     B
3   Zain      7      6     B
4   Hina     10      9     A


Try It - add Total column, save as student_scores_total.csv, print top student

In [15]:
df2['Total'] = df2['Quiz1'] + df2['Quiz2']
df2.to_csv('student_scores_total.csv', index=False)

top_student = df2.loc[df2['Total'].idxmax()]
print(df2)
print()
print(top_student)

    Name  Quiz1  Quiz2  Total
0    Ali      8      7     15
1   Sara      9     10     19
2  Bilal      6      8     14
3   Zain      7      6     13
4   Hina     10      9     19

Name     Sara
Quiz1       9
Quiz2      10
Total      19
Name: 1, dtype: object


## End of Lab Exercises

#### 1. Data Types & Operators

In [17]:
celsius = 36.5
fahrenheit = celsius * 9/5 + 32

print('Celsius:', celsius, type(celsius))
print('Fahrenheit:', fahrenheit, type(fahrenheit))

Celsius: 36.5 <class 'float'>
Fahrenheit: 97.7 <class 'float'>


#### 2. Control Structures

In [16]:
fizzbuzz_count = 0

for i in range(1, 51):
    if i % 3 == 0 and i % 5 == 0:
        print('FizzBuzz')
        fizzbuzz_count += 1
    elif i % 3 == 0:
        print('Fizz')
    elif i % 5 == 0:
        print('Buzz')
    else:
        print(i)

print('FizzBuzz occurred:', fizzbuzz_count, 'times')

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
FizzBuzz occurred: 3 times


#### 3. Arrays

In [19]:
exam_scores = array('i', [78, 85, 90, 62, 74, 88, 95, 69, 81, 73])

total = 0
for score in exam_scores:
    total += score

average = total / len(exam_scores)

print('Scores:', exam_scores)
print('Average:', average)

Scores: array('i', [78, 85, 90, 62, 74, 88, 95, 69, 81, 73])
Average: 79.5


#### 4. NumPy

In [20]:
random_matrix = np.random.randint(1, 101, size=(4, 4))

print(random_matrix)
print('Transpose:\n', random_matrix.T)
print('Row sums:', random_matrix.sum(axis=1))
print('Column sums:', random_matrix.sum(axis=0))

[[ 96  91  49 100]
 [ 47  52  11  25]
 [ 59  30  21  87]
 [ 88  32   3  97]]
Transpose:
 [[ 96  47  59  88]
 [ 91  52  30  32]
 [ 49  11  21   3]
 [100  25  87  97]]
Row sums: [336 135 197 220]
Column sums: [290 205  84 309]


#### 5. Lists, Tuples & Sets

In [21]:
recipe_a = ['tomato', 'onion', 'garlic', 'chili', 'salt', 'oil']
recipe_b = ['onion', 'garlic', 'ginger', 'yogurt', 'salt', 'cumin']

set_a = set(recipe_a)
set_b = set(recipe_b)

print('Common:', set_a & set_b)
print('Unique to A:', set_a - set_b)
print('Unique to B:', set_b - set_a)
print('Combined:', set_a | set_b)

Common: {'garlic', 'onion', 'salt'}
Unique to A: {'chili', 'tomato', 'oil'}
Unique to B: {'yogurt', 'cumin', 'ginger'}
Combined: {'yogurt', 'garlic', 'salt', 'oil', 'onion', 'cumin', 'ginger', 'tomato', 'chili'}


#### 6. Pandas

In [17]:
sales_data = {
    'Product': ['Notebook', 'Pen', 'Backpack', 'Calculator', 'Water Bottle'],
    'Quantity': [50, 120, 15, 30, 40],
    'Price': [2.5, 0.5, 25.0, 12.0, 5.0],
}

sales_df = pd.DataFrame(sales_data)
sales_df['Total'] = sales_df['Quantity'] * sales_df['Price']
sales_df.to_csv('sales_data.csv', index=False)

sales_df_read = pd.read_csv('sales_data.csv')
top_product = sales_df_read.loc[sales_df_read['Total'].idxmax()]

print(sales_df_read)
print()
print(top_product)

        Product  Quantity  Price  Total
0      Notebook        50    2.5  125.0
1           Pen       120    0.5   60.0
2      Backpack        15   25.0  375.0
3    Calculator        30   12.0  360.0
4  Water Bottle        40    5.0  200.0

Product     Backpack
Quantity          15
Price           25.0
Total          375.0
Name: 2, dtype: object


#### 7. Capstone - Class Gradebook

In [18]:
student_names = ['Ali', 'Sara', 'Bilal', 'Zain', 'Hina',
                  'Omar', 'Ayesha', 'Fahad', 'Mahnoor', 'Usman']

quiz_scores = np.random.randint(60, 101, size=(10, 3))
averages = quiz_scores.mean(axis=1)

def assign_grade(avg):
    if avg >= 90:
        return 'A'
    elif avg >= 80:
        return 'B'
    elif avg >= 70:
        return 'C'
    else:
        return 'F'

grades = [assign_grade(a) for a in averages]

gradebook = pd.DataFrame({
    'Name': student_names,
    'Average': averages,
    'Grade': grades
})

gradebook.to_csv('gradebook.csv', index=False)

print(gradebook)
print()
print(gradebook[gradebook['Grade'] == 'A'])

      Name    Average Grade
0      Ali  92.333333     A
1     Sara  68.333333     F
2    Bilal  75.666667     C
3     Zain  80.666667     B
4     Hina  85.666667     B
5     Omar  74.000000     C
6   Ayesha  72.666667     C
7    Fahad  73.666667     C
8  Mahnoor  75.333333     C
9    Usman  86.000000     B

  Name    Average Grade
0  Ali  92.333333     A
